# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:50
# pylint: skip-file
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleRobotAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=2048)),
                ('tags', models.CharField(blank=True, max_length=2048, null=True)),
                ('action_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('probe', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('generated', models.DateTimeField()),
                ('dismissed', models.DateTimeField(blank=True, null=True)),
                ('manually_dismissed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024, unique=True)),
                ('contents', models.TextField(max_length=1048576)),
                ('added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('device_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('description', models.TextField(blank=True, max_length=1048576, null=True)),
                ('config_last_fetched', models.DateTimeField(blank=True, null=True)),
                ('config_last_user_agent', models.CharField(blank=True, max_length=1024, null=True)),
                ('hash_key', models.CharField(blank=True, max_length=128, null=True)),
                ('first_reading_timestamp', models.BigIntegerField(default=0)),
                ('last_reading_timestamp', models.BigIntegerField(default=0)),
                ('mute_alerts', models.BooleanField(default=False)),
                ('test_device', models.BooleanField(default=False)),
                ('performance_metadata', models.TextField(default=b'{}', max_length=1048576)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='purple_robot.PurpleRobotConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotDeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('group_id', models.SlugField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, max_length=1048576, null=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='purple_robot.PurpleRobotConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotDeviceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1024)),
                ('added', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='purple_robot.PurpleRobotDevice')),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1024)),
                ('name', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('logged', models.DateTimeField(db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=1024)),
                ('payload', models.TextField(blank=True, max_length=8388608, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotExportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probes', models.TextField(blank=True, max_length=8196, null=True)),
                ('users', models.TextField(blank=True, max_length=8196, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('export_file', models.FileField(blank=True, upload_to=b'export_files')),
                ('destination', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(choices=[(b'pending', b'Pending'), (b'processing', b'Processing'), (b'finished', b'Finished'), (b'error', b'Error')], default=b'pending', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField(max_length=8388608)),
                ('process_tags', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=1024)),
                ('errors', models.TextField(blank=True, max_length=65536, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=1024)),
                ('payload', models.TextField(max_length=8388608)),
                ('logged', models.DateTimeField(db_index=True)),
                ('guid', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('size', models.IntegerField(db_index=True, default=0)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=b'reading_attachments')),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_id', models.CharField(max_length=1024)),
                ('generated', models.DateTimeField()),
                ('mime_type', models.CharField(max_length=1024)),
                ('report_file', models.FileField(blank=True, upload_to=b'report_files')),
            ],
        ),
        migrations.CreateModel(
            name='PurpleRobotTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=1024, unique=True)),
                ('probe', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_id', models.CharField(max_length=1024)),
                ('frequency', models.FloatField(default=1.0)),
                ('report', models.TextField(default=b'{}')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AlterIndexTogether(
            name='purplerobotreading',
            index_together=set([('probe', 'logged', 'user_id'), ('logged', 'user_id'), ('probe', 'user_id')]),
        ),
        migrations.AddField(
            model_name='purplerobotdevice',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='purple_robot.PurpleRobotDeviceGroup'),
        ),
    ]
